# Generated by Django 4.2.2 on 2023-06-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_alter_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.CharField(max_length=1028, null=True),
        ),
    ]
